image: alpine:3

stages:
  - setup
  - trigger

setup:
  stage: setup

  script:
    - |
      if [ ! -f .gitlab-ci-template.yml ]; then
        wget -O .gitlab-ci-template.yml https://gitlab.com/tozd/docker/base/-/raw/master/.gitlab-ci-template.yml
      fi
      for FILE in *.dockerfile ; do
        TAG="$(basename "$FILE" .dockerfile)"
        sed "s/__TAG__/$TAG/g" .gitlab-ci-template.yml >> generated-gitlab-ci.yml
      done

  artifacts:
    paths:
      - generated-gitlab-ci.yml

trigger:
  stage: trigger

  trigger:
    strategy: depend
    include:
      - artifact: generated-gitlab-ci.yml
        job: setup
