default:
  image: docker:19

  services:
    - docker:19-dind

  before_script:
    - docker info
    - echo "$CI_JOB_TOKEN" | docker login --username gitlab-ci-token --password-stdin "$CI_REGISTRY"
    # Workaround for: https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1736
    - apk add --no-cache git
    - git checkout-index --all --prefix umask-fix-checkout/
    - cd umask-fix-checkout/

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
