default:
  image: docker:19

  services:
    - docker:19-dind

  before_script:
    - docker info
    - echo "$CI_JOB_TOKEN" | docker login --username gitlab-ci-token --password-stdin "$CI_REGISTRY"

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  # Workaround for: https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1736
  CI_PRE_CLONE_SCRIPT: "umask 022"
  GIT_SUBMODULE_STRATEGY: recursive
