image: alpine:3

stages:
  - setup
  - trigger

setup:
  stage: setup

  script:
    - |
      for FILE in *.dockerfile ; do
        TAG="$(basename "$FILE" .dockerfile)"
        sed "s/__TAG__/$TAG/g" .gitlab-ci-template.yml >> generated-gitlab-ci.yml
      done

  artifacts:
    paths:
      - generated-gitlab-ci.yml

trigger:
  stage: trigger

  trigger:
    include:
      - artifact: generated-gitlab-ci.yml
        job: setup
